# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk11

#https://dzone.com/articles/travis-ci-tutorial-java-projects
cache:
  directories:
  - $HOME/.m2

# https://docs.travis-ci.com/user/database-setup/#PostgreSQL
#addons:
#  postgresql: "9.6"

#https://stackoverflow.com/questions/55161807/travis-ci-not-connecting-to-postgresql-11-2:
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11

before_script:
  - psql --version
  - psql -c 'CREATE DATABASE topjava;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
#script: bundle exec rake spec
services:
  - postgresql

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
  - master

#https://docs.travis-ci.com/user/environment-variables#Default-Environment-Variables
env:
- TOPJAVA_ROOT=$TRAVIS_BUILD_DIR

# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
#  email: false